FROM node:lts-bullseye-slim AS build

WORKDIR /opt
ENV REACT_APP_API_URL=${REACT_APP_API_URL}
COPY client /opt
RUN npm ci && npm run build

FROM nginx:alpine
COPY --from=build /opt/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]

