apiVersion: v1
kind: Service
metadata:
  name: api-backend-deployment  
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
    - protocol: TCP
      port: 8010
      targetPort: 8010
  type: ClusterIP
