apiVersion: v1
kind: Service
metadata:
  name: client-frontend-deployment
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30005
